### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by AlinaKulishdp** [demmy/CS2_Project#13]
IRepository<T> - AlinaKulishdp 
IPersonalInfoRepository<PersonalInfo> - AlinaKulishdp 
IContactsInfoRepository<ContactsInfo>  - AlinaKulishdp 
ICustomerRepository<Customer>  - AlinaKulishdp 
IUserRepository<Repository>  - SmolenskiyK
IOrderRepository<Order>  - SmolenskiyK
IOrderStatusRepository<OrderStatus>-KrasaE
IGoodsRepository<Goods>   - AlinaKulishdp 
IGoodsRowRepository<GoodsRow>   - AlinaKulishdp 
IRoleRepository<Role>  - SmolenskiyK
IPermessionRepository<Permission>  - vbre
ICommentRepository<Comment>-KrasaE
IProductCategoryRepository<ProductCategory>   - AlinaKulishdp

**Comment by vbre** [comment]
it isn't fair that you left me only one interface to implement:)
